In [3]:
from __future__ import annotations

from pathlib import Path
import sys

project_root = Path.cwd().resolve().parent
sys.path.append(str(project_root))

import pandas as pd
import numpy as np
import ast

from config import get_settings
from tmdb_movie.utils.api import get_movies_dataframe_from_ids

In [5]:
# Download movies
MOVIE_IDS = [
    0,
    299534,
    19995,
    140607,
    299536,
    597,
    135397,
    420818,
    24428,
    168259,
    99861,
    284054,
    12445,
    181808,
    330457,
    351286,
    109445,
    321612,
    260513,
]

df = get_movies_dataframe_from_ids(settings=get_settings(), movie_ids=MOVIE_IDS)

In [6]:
df.head()

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,NaN,NaN,NaN,NaN,[],NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,[],NaN,NaN,Movie 0 not found,NaN,NaN,NaN
1,False,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.marvel.com/movies/avengers-endgame,299534,tt4154796,en,Avengers: Endgame,...,2019-04-24,2.799439e+09,181.0,"[{'iso_639_1': 'en', 'name': 'English', 'engli...",Released,Avenge the fallen.,Avengers: Endgame,False,8.20,27363.0
2,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000.0,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.avatar.com/movies/avatar,19995,tt0499549,en,Avatar,...,2009-12-16,2.923706e+09,162.0,"[{'iso_639_1': 'en', 'name': 'English', 'engli...",Released,Enter the world of Pandora.,Avatar,False,7.60,33599.0
3,False,/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,140607,tt2488496,en,Star Wars: The Force Awakens,...,2015-12-15,2.068224e+09,136.0,"[{'iso_639_1': 'en', 'name': 'English', 'engli...",Released,Every generation has a story.,Star Wars: The Force Awakens,False,7.25,20342.0
4,False,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000.0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.marvel.com/movies/avengers-infinit...,299536,tt4154756,en,Avengers: Infinity War,...,2018-04-25,2.052415e+09,149.0,"[{'iso_639_1': 'en', 'name': 'English', 'engli...",Released,Destiny arrives all the same.,Avengers: Infinity War,False,8.20,31596.0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  18 non-null     object
 1   backdrop_path          18 non-null     str
 2   belongs_to_collection  16 non-null     str
 3   budget                 18 non-null     float64
 4   genres                 19 non-null     str
 5   homepage               18 non-null     str
 6   id                     19 non-null     int64
 7   imdb_id                18 non-null     str
 8   original_language      18 non-null     str
 9   original_title         18 non-null     str
 10  overview               18 non-null     str
 11  popularity             18 non-null     float64
 12  poster_path            18 non-null     str
 13  production_companies   19 non-null     str
 14  production_countries   19 non-null     str
 15  release_date           18 non-null     str
 16  revenue                18 non-null     float64
 17  runtime                18 non-null     float64
 18  spoken_languages       19 non-null     str
 19  status                 18 non-null     str
 20  tagline                18 non-null     str
 21  title                  19 non-null     str
 22  video                  18 non-null     object
 23  vote_average           18 non-null     float64
 24  vote_count             18 non-null     float64
dtypes: float64(6), int64(1), object(2), str(16)
memory usage: 23.7+ KB

In [9]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,1.800000e+01,19.000000,18.000000,1.800000e+01,18.000000,18.000000,18.000000
mean,2.137778e+08,182139.578947,16.916744,1.691832e+09,138.055556,7.391111,20805.444444
std,6.195972e+07,136090.306553,10.203019,5.210623e+08,23.848720,0.509729,8075.316765
min,1.250000e+08,0.000000,8.661500,1.243226e+09,102.000000,6.532000,10185.000000
25%,1.625000e+08,62144.500000,10.686950,1.334902e+09,125.250000,7.129500,14148.000000
50%,2.000000e+08,168259.000000,12.501100,1.484542e+09,135.500000,7.260000,20863.000000
75%,2.430000e+08,299535.000000,18.150350,1.957196e+09,147.500000,7.826500,26206.000000
max,3.560000e+08,420818.000000,47.958800,2.923706e+09,194.000000,8.200000,36446.000000

In [20]:
# Missing % and Unique values
missing_check = (
    df.isna()
    .mean()
    .mul(100)
    .to_frame(name='missing_pct')
    .assign(unique_count=df.nunique())
    .sort_values('missing_pct', ascending=False)
)

missing_check

                       missing_pct  unique_count
belongs_to_collection    15.789474            10
adult                     5.263158             1
backdrop_path             5.263158            18
budget                    5.263158            13
homepage                  5.263158            18
original_language         5.263158             1
imdb_id                   5.263158            18
overview                  5.263158            18
original_title            5.263158            18
vote_count                5.263158            18
vote_average              5.263158            17
popularity                5.263158            18
poster_path               5.263158            18
revenue                   5.263158            18
release_date              5.263158            18
status                    5.263158             1
runtime                   5.263158            16
tagline                   5.263158            18
video                     5.263158             1
id                        0.000000            19
genres                    0.000000            14
production_companies      0.000000            14
production_countries      0.000000             4
spoken_languages          0.000000            11
title                     0.000000            19

In [24]:
# Columns with objects or lists
json_cols = ['belongs_to_collection', 'genres', 'production_countries',
             'production_companies', 'spoken_languages']

for col in json_cols:
    if col in df.columns:
        sample_val = df[col].iloc[2]
        print(f"Column: {col} | Type: {type(sample_val)}")
        print(f"Sample Content: {sample_val}\n")

Column: belongs_to_collection | Type: <class 'str'>
Sample Content: {'id': 87096, 'name': 'Avatar Collection', 'poster_path': '/3C5brXxnBxfkeKWwA1Fh4xvy4wr.jpg', 'backdrop_path': '/6qkJLRCZp9Y3ovXti5tSuhH0DpO.jpg'}

Column: genres | Type: <class 'str'>
Sample Content: [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 878, 'name': 'Science Fiction'}]

Column: production_countries | Type: <class 'str'>
Sample Content: [{'iso_3166_1': 'US', 'name': 'United States of America'}, {'iso_3166_1': 'GB', 'name': 'United Kingdom'}]

Column: production_companies | Type: <class 'str'>
Sample Content: [{'id': 444, 'name': 'Dune Entertainment', 'logo_path': None, 'origin_country': 'US'}, {'id': 574, 'name': 'Lightstorm Entertainment', 'logo_path': '/8wdmrfGcDx3TJxYiiDksLzAW4pB.png', 'origin_country': 'US'}, {'id': 25, 'name': '20th Century Fox', 'logo_path': '/qZCc1lty5FzX30aOCVRBLzaVmcp.png', 'origin_country': 'US'}, {'id': 133789, 'name': 'Ingenious Film Partners', 'logo_path': '/bJdeIb1ET3BkyodAASVDq1x3mls.png', 'origin_country': 'GB'}]

Column: spoken_languages | Type: <class 'str'>
Sample Content: [{'iso_639_1': 'en', 'name': 'English', 'english_name': 'English'}, {'iso_639_1': 'es', 'name': 'Español', 'english_name': 'Spanish'}]

In [25]:
inspection_cats = (
    df[['status', 'original_language']]
    .melt(var_name='column', value_name='value')
    .value_counts()
    .to_frame(name='count')
)

print("--- Categorical Distribution ---")
display(inspection_cats)

--- Categorical Distribution ---

                            count
column            value
status            Released     18
original_language en           18