In [1]:
from __future__ import annotations

import sys
from pathlib import Path

project_root = Path.cwd().resolve().parent
sys.path.append(str(project_root))

from config import get_settings
from tmdb_movie.utils.api import get_movies_dataframe_from_ids

In [2]:
MOVIE_IDS = [
    0,
    # 299534,
    # 19995,
    # 140607,
    # 299536,
    # 597,
    # 135397,
    # 420818,
    # 24428,
    # 168259,
    # 99861,
    # 284054,
    # 12445,
    # 181808,
    # 330457,
    # 351286,
    # 109445,
    # 321612,
    # 260513,
]

df = get_movies_dataframe_from_ids(settings=get_settings(), movie_ids=MOVIE_IDS)

In [3]:
df.head()

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,True,None,None,None,[],None,0,None,None,None,...,None,None,None,[],None,None,Movie 0 not found,None,None,None

In [8]:
display(df.describe())

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,1.800000e+01,18.000000,18.000000,1.800000e+01,18.000000,18.000000,18.000000
mean,2.137778e+08,192258.444444,18.269261,1.691832e+09,138.055556,7.394667,20794.611111
std,6.195972e+07,132476.949284,10.748166,5.210623e+08,23.848720,0.516215,8063.838913
min,1.250000e+08,597.000000,8.666600,1.243226e+09,102.000000,6.532000,10183.000000
25%,1.625000e+08,102257.000000,10.388500,1.334902e+09,125.250000,7.127250,14142.250000
50%,2.000000e+08,175033.500000,16.113050,1.484542e+09,135.500000,7.260000,20854.500000
75%,2.430000e+08,299535.500000,19.754300,1.957196e+09,147.500000,7.827250,26199.000000
max,3.560000e+08,420818.000000,50.907700,2.923706e+09,194.000000,8.235000,36366.000000